export const FACULTY_ACTIONS = [
  { label: "Accept", value: "ACCEPT" },
  { label: "Acknowledge", value: "ACKNOWLEDGE" },
  { label: "Acquire", value: "ACQUIRE" },
  { label: "Amend", value: "AMEND" },
  { label: "Amortize", value: "AMORTIZE" },
  { label: "Answer", value: "ANSWER" },
  { label: "Appeal", value: "APPEAL" },
  { label: "Appoint", value: "APPOINT" },
  { label: "Approve", value: "APPROVE" },
  { label: "Assign", value: "ASSIGN" },
  { label: "Attend", value: "ATTEND" },
  { label: "Cancel", value: "CANCEL" },
  { label: "Challenge", value: "CHALLENGE" },
  { label: "Close", value: "CLOSE" },
  { label: "Collect", value: "COLLECT" },
  { label: "Comply", value: "COMPLY" },
  { label: "Delegate", value: "DELEGATE" },
  { label: "Deposit", value: "DEPOSIT" },
  { label: "Disclose", value: "DISCLOSE" },
  { label: "Dispose", value: "DISPOSE" },
  { label: "Dissolve", value: "DISSOLVE" },
  { label: "Encumber", value: "ENCUMBER" },
  { label: "Endorse", value: "ENDORSE" },
  { label: "Establish", value: "ESTABLISH" },
  { label: "Execute", value: "EXECUTE" },
  { label: "File", value: "FILE" },
  { label: "Grant", value: "GRANT" },
  { label: "Hire", value: "HIRE" },
  { label: "Incorporate", value: "INCORPORATE" },
  { label: "Inspect", value: "INSPECT" },
  { label: "Interrupt", value: "INTERRUPT" },
  { label: "Issue", value: "ISSUE" },
  { label: "Lease in", value: "LEASE_IN" },
  { label: "Lease out", value: "LEASE_OUT" },
  { label: "Liquidate", value: "LIQUIDATE" },
  { label: "Litigate", value: "LITIGATE" },
  { label: "Manage", value: "MANAGE" },
  { label: "Negotiate", value: "NEGOTIATE" },
  { label: "Open", value: "OPEN" },
  { label: "Operate electronically", value: "OPERATE_ELECTRONICALLY" },
  { label: "Overdraw", value: "OVERDRAW" },
  { label: "Pay", value: "PAY" },
  { label: "Pay in", value: "PAY_IN" },
  { label: "Receive", value: "RECEIVE" },
  { label: "Redeem", value: "REDEEM" },
  { label: "Register", value: "REGISTER" },
  { label: "Release", value: "RELEASE" },
  { label: "Renew", value: "RENEW" },
  { label: "Repair", value: "REPAIR" },
  { label: "Represent", value: "REPRESENT" },
  { label: "Request", value: "REQUEST" },
  { label: "Revoke", value: "REVOKE" },
  { label: "Settle", value: "SETTLE" },
  { label: "Sign", value: "SIGN" },
  { label: "Submit to arbitration", value: "SUBMIT_TO_ARBITRATION" },
  { label: "Subscribe", value: "SUBSCRIBE" },
  { label: "Terminate", value: "TERMINATE" },
  { label: "Trade", value: "TRADE" },
  { label: "Transfer", value: "TRANSFER" },
  { label: "Verify", value: "VERIFY" },
  { label: "Vote", value: "VOTE" },
  { label: "Waive", value: "WAIVE" },
  { label: "Withdraw", value: "WITHDRAW" },
];

export const FACULTY_OBJECTS_CATEGORY = [
  { label: "Accounting", value: "ACCOUNTING" },
  { label: "Accounting books", value: "ACCOUNTING_BOOKS" },
  { label: "Account statement", value: "ACCOUNT_STATEMENT" },
  { label: "Administrative decision", value: "ADMINISTRATIVE_DECISION" },
  { label: "Administrative file", value: "ADMINISTRATIVE_FILE" },
  { label: "Appraisal", value: "APPRAISAL" },
  { label: "Bank account", value: "BANK_ACCOUNT" },
  { label: "Bargaining committee", value: "BARGAINING_COMMITTEE" },
  { label: "Bill of exchange", value: "BILL_OF_EXCHANGE" },
  { label: "Bill of lading", value: "BILL_OF_LADING" },
  { label: "Brief", value: "BRIEF" },
  { label: "Cargo", value: "CARGO" },
  { label: "Certificate", value: "CERTIFICATE" },
  { label: "Certificate of origin", value: "CERTIFICATE_OF_ORIGIN" },
  { label: "Check", value: "CHECK" },
  { label: "Checkbook", value: "CHECKBOOK" },
  { label: "Collective agreement", value: "COLLECTIVE_AGREEMENT" },
  { label: "Company", value: "COMPANY" },
  { label: "Contract", value: "CONTRACT" },
  { label: "Corporate meeting", value: "CORPORATE_MEETING" },
  { label: "Corporate shareholding", value: "CORPORATE_SHAREHOLDING" },
  { label: "Correspondence", value: "CORRESPONDENCE" },
  { label: "Counterclaim", value: "COUNTERCLAIM" },
  { label: "Credit line", value: "CREDIT_LINE" },
  { label: "Customs declaration", value: "CUSTOMS_DECLARATION" },
  { label: "Customs inspection", value: "CUSTOMS_INSPECTION" },
  { label: "Damages", value: "DAMAGES" },
  { label: "Debt", value: "DEBT" },
  { label: "Defense", value: "DEFENSE" },
  { label: "Delegation", value: "DELEGATION" },
  { label: "Derivative contract", value: "DERIVATIVE_CONTRACT" },
  { label: "Dividends", value: "DIVIDENDS" },
  { label: "Documentary credit", value: "DOCUMENTARY_CREDIT" },
  { label: "Easement", value: "EASEMENT" },
  { label: "Employment relationship", value: "EMPLOYMENT_RELATIONSHIP" },
  { label: "Energy equipment", value: "ENERGY_EQUIPMENT" },
  { label: "Energy supply contract", value: "ENERGY_SUPPLY_CONTRACT" },
  { label: "Evidence", value: "EVIDENCE" },
  { label: "Expert", value: "EXPERT" },
  { label: "Expert report", value: "EXPERT_REPORT" },
  { label: "Export refund", value: "EXPORT_REFUND" },
  { label: "Fees", value: "FEES" },
  { label: "Financial statements", value: "FINANCIAL_STATEMENTS" },
  { label: "Fine", value: "FINE" },
  { label: "Force majeure", value: "FORCE_MAJEURE" },
  { label: "Foreign currency", value: "FOREIGN_CURRENCY" },
  { label: "Formal demand", value: "FORMAL_DEMAND" },
  { label: "Fruits", value: "FRUITS" },
  { label: "Fuel", value: "FUEL" },
  { label: "Funds", value: "FUNDS" },
  { label: "Grace period", value: "GRACE_PERIOD" },
  { label: "Guarantee", value: "GUARANTEE" },
  { label: "Hearing", value: "HEARING" },
  { label: "Inspection", value: "INSPECTION" },
  { label: "Insurance policy", value: "INSURANCE_POLICY" },
  { label: "Interrogatory", value: "INTERROGATORY" },
  { label: "Inventory", value: "INVENTORY" },
  { label: "Invoice", value: "INVOICE" },
  { label: "Judge", value: "JUDGE" },
  { label: "Judicial notice", value: "JUDICIAL_NOTICE" },
  { label: "Jurisdiction", value: "JURISDICTION" },
  { label: "Labor claim", value: "LABOR_CLAIM" },
  { label: "Lease agreement", value: "LEASE_AGREEMENT" },
  { label: "Legal notice", value: "LEGAL_NOTICE" },
  { label: "Letter rogatory", value: "LETTER_ROGATORY" },
  { label: "Livestock", value: "LIVESTOCK" },
  { label: "Loan", value: "LOAN" },
  { label: "Management contracts", value: "MANAGEMENT_CONTRACTS" },
  { label: "Merchandise", value: "MERCHANDISE" },
  { label: "Mortgage", value: "MORTGAGE" },
  { label: "Motion", value: "MOTION" },
  { label: "Movable assets", value: "MOVABLE_ASSETS" },
  { label: "Mutual fund units", value: "MUTUAL_FUND_UNITS" },
  { label: "Negotiable obligations", value: "NEGOTIABLE_OBLIGATIONS" },
  { label: "Notarial certificate", value: "NOTARIAL_CERTIFICATE" },
  { label: "Novation", value: "NOVATION" },
  { label: "Oath", value: "OATH" },
  { label: "Obligation", value: "OBLIGATION" },
  { label: "Patent", value: "PATENT" },
  { label: "Payment order", value: "PAYMENT_ORDER" },
  { label: "Permit", value: "PERMIT" },
  { label: "Plan and form", value: "PLAN_AND_FORM" },
  { label: "Pledge", value: "PLEDGE" },
  { label: "Possession", value: "POSSESSION" },
  { label: "Power of attorney", value: "POWER_OF_ATTORNEY" },
  { label: "Precautionary measure", value: "PRECAUTIONARY_MEASURE" },
  { label: "Promissory note", value: "PROMISSORY_NOTE" },
  { label: "Protest", value: "PROTEST" },
  { label: "Public instrument", value: "PUBLIC_INSTRUMENT" },
  { label: "Real estate", value: "REAL_ESTATE" },
  { label: "Receipt", value: "RECEIPT" },
  { label: "Receivables", value: "RECEIVABLES" },
  { label: "Rent", value: "RENT" },
  { label: "Rights", value: "RIGHTS" },
  { label: "Safe deposit box", value: "SAFE_DEPOSIT_BOX" },
  { label: "Salary", value: "SALARY" },
  { label: "Securities", value: "SECURITIES" },
  { label: "Services", value: "SERVICES" },
  { label: "Special domicile", value: "SPECIAL_DOMICILE" },
  { label: "Statute of limitations", value: "STATUTE_OF_LIMITATIONS" },
  { label: "Subrogation", value: "SUBROGATION" },
  { label: "Sworn statement", value: "SWORN_STATEMENT" },
  { label: "Tax obligation", value: "TAX_OBLIGATION" },
  { label: "Tax relief", value: "TAX_RELIEF" },
  { label: "Termination notice", value: "TERMINATION_NOTICE" },
  { label: "Time deposit", value: "TIME_DEPOSIT" },
  { label: "Toll", value: "TOLL" },
  { label: "Trademark", value: "TRADEMARK" },
  { label: "Treasury bills", value: "TREASURY_BILLS" },
  { label: "Union dues", value: "UNION_DUES" },
  { label: "Utility service", value: "UTILITY_SERVICE" },
  { label: "Vehicle registration", value: "VEHICLE_REGISTRATION" },
  { label: "Vehicles", value: "VEHICLES" },
  { label: "Witness", value: "WITNESS" },
];
